# Site settings
title: Kelly Gola, PhD
description: Data Science, Behavioral Research
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kelly Gola, PhD
user_description: Understanding human behavior through data.
user_title: Data Science, Research Science 
email: kagola7@gmail.com
twitter_username: https://twitter.com/Kell_Belle77
github_username:  https://github.com/kgola

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
